# Auto-generated by automation/nightly/build_monitor_list.py
# SOURCE_CSV = '/home/runner/work/cs-skins-monitoring-bot/cs-skins-monitoring-bot/automation_runtime/risk_candidates_latest.csv'
# PROFILE = 'risk_plus_high_cv'
# TOTAL_RISK_ROWS = 266
# RISK_PASSED = 266
# HIGH_CV_PASSED = 155
# N_OUTPUT_ITEMS = 31

ITEMS = [
    "USP-S | Jawbreaker (Field-Tested)",
    "AK-47 | Slate (Well-Worn)",
    "AK-47 | Wintergreen (Minimal Wear)",
    "M4A1-S | Electrum (Minimal Wear)",
    "P2000 | Wicked Sick (Field-Tested)",
    "AK-47 | Slate (Battle-Scarred)",
    "AK-47 | Slate (Minimal Wear)",
    "M4A1-S | Black Lotus (Minimal Wear)",
    "P250 | Visions (Field-Tested)",
    "AK-47 | Elite Build (Minimal Wear)",
    "Desert Eagle | Mulberry (Field-Tested)",
    "AK-47 | Ice Coaled (Battle-Scarred)",
    "AK-47 | Searing Rage (Battle-Scarred)",
    "Glock-18 | Shinobu (Battle-Scarred)",
    "USP-S | Jawbreaker (Battle-Scarred)",
    "AK-47 | Searing Rage (Minimal Wear)",
    "USP-S | Jawbreaker (Minimal Wear)",
    "AWP | Duality (Battle-Scarred)",
    "AWP | Atheris (Minimal Wear)",
    "AWP | Ice Coaled (Field-Tested)",
    "Glock-18 | Shinobu (Minimal Wear)",
    "Dual Berettas | Melondrama (Minimal Wear)",
    "AK-47 | Midnight Laminate (Battle-Scarred)",
    "UMP-45 | Wild Child (Well-Worn)",
    "FAMAS | Rapid Eye Movement (Minimal Wear)",
    "UMP-45 | Wild Child (Battle-Scarred)",
    "USP-S | Alpine Camo (Factory New)",
    "P2000 | Wicked Sick (Battle-Scarred)",
    "UMP-45 | K.O. Factory (Minimal Wear)",
    "AUG | Eye of Zapems (Field-Tested)",
    "XM1014 | Entombed (Minimal Wear)",
]
