"""Build model coverage and a backfill queue from risk-passed candidates."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from automation.config import load_json_config, nightly_defaults, path_from_config
from automation.risk_filters import repo_root_from


def parse_args() -> argparse.Namespace:
    root = repo_root_from(Path(__file__))
    parser = argparse.ArgumentParser(description="Build model coverage report and backfill queue.")
    parser.add_argument(
        "--config",
        type=Path,
        default=root / "automation" / "configs" / "nightly.json",
        help="Nightly automation JSON config.",
    )
    parser.add_argument("--risk-candidates-csv", type=Path, default=None)
    parser.add_argument("--summary-csv", type=Path, default=None)
    parser.add_argument("--fit-json", type=Path, default=None)
    parser.add_argument("--out-coverage-csv", type=Path, default=None)
    parser.add_argument("--out-queue-csv", type=Path, default=None)
    parser.add_argument("--out-queue-items-py", type=Path, default=None)
    return parser.parse_args()


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")


def load_fit_payload(path: Path) -> dict:
    require_file(path, "fit JSON")
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    per_skin = payload.get("per_skin")
    if not isinstance(per_skin, dict):
        raise ValueError(f"{path} must contain a per_skin object")
    return payload


def numeric_column(df: pd.DataFrame, column: str) -> pd.Series:
    if column not in df.columns:
        return pd.Series(pd.NA, index=df.index, dtype="Float64")
    return pd.to_numeric(df[column], errors="coerce")


def fit_clean_points(fit_row: object) -> int | None:
    if not isinstance(fit_row, dict):
        return None
    value = fit_row.get("n_clean", fit_row.get("n_raw"))
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def reason_text(row: pd.Series) -> str:
    reasons: list[str] = []
    if not bool(row["has_summary"]):
        reasons.append("missing_summary")
    if not bool(row["has_fit"]):
        reasons.append("missing_fit_json")
    if bool(row["has_summary"]) and not bool(row["summary_ready"]):
        reasons.append("low_summary_n_listings")
    if bool(row["has_fit"]) and not bool(row["fit_ready"]):
        reasons.append("low_fit_clean_points")
    return ", ".join(reasons)


def write_items_py(items: list[str], path: Path, *, source_csv: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by automation/nightly/build_model_backfill_queue.py",
        f"# SOURCE_CSV = {str(source_csv)!r}",
        f"# N_OUTPUT_ITEMS = {len(items)}",
        "",
        "ITEMS = [",
    ]
    lines.extend(f"    {json.dumps(item, ensure_ascii=False)}," for item in items)
    lines.append("]")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    config_path = args.config.resolve()
    config = load_json_config(config_path, nightly_defaults())
    coverage_cfg = config.get("model_coverage", {})
    min_summary_n = int(coverage_cfg.get("min_summary_n_listings", 3))
    min_fit_clean = int(coverage_cfg.get("min_fit_clean_points", 5))

    risk_candidates_csv = (
        args.risk_candidates_csv.resolve()
        if args.risk_candidates_csv
        else path_from_config(config, "risk_candidates_csv")
    )
    summary_csv = args.summary_csv.resolve() if args.summary_csv else path_from_config(config, "summary_csv")
    fit_json = args.fit_json.resolve() if args.fit_json else path_from_config(config, "fit_json")
    coverage_csv = (
        args.out_coverage_csv.resolve()
        if args.out_coverage_csv
        else path_from_config(config, "model_coverage_csv")
    )
    queue_csv = args.out_queue_csv.resolve() if args.out_queue_csv else path_from_config(config, "model_backfill_queue_csv")
    queue_items_py = (
        args.out_queue_items_py.resolve()
        if args.out_queue_items_py
        else path_from_config(config, "model_backfill_queue_items_py")
    )

    require_file(risk_candidates_csv, "risk candidates CSV")
    require_file(summary_csv, "data_skins_big summary CSV")
    candidates = pd.read_csv(risk_candidates_csv)
    if "item" not in candidates.columns:
        raise KeyError(f"{risk_candidates_csv} must contain an 'item' column")

    summary = pd.read_csv(summary_csv)
    if "item" not in summary.columns:
        raise KeyError(f"{summary_csv} must contain an 'item' column")
    summary = summary.drop_duplicates(subset=["item"], keep="last").copy()
    summary["item"] = summary["item"].astype(str)
    summary["summary_n_listings"] = numeric_column(summary, "n_listings")
    summary_keep = [
        c
        for c in [
            "item",
            "summary_n_listings",
            "pred_cv",
            "pred_range_over_mean",
            "pred_mean",
            "pred_min",
            "pred_max",
        ]
        if c in summary.columns
    ]

    fit_payload = load_fit_payload(fit_json)
    fit_rows = []
    for item, fit_row in fit_payload.get("per_skin", {}).items():
        fit_rows.append({"item": str(item), "fit_n_clean": fit_clean_points(fit_row)})
    fit = pd.DataFrame(fit_rows)
    if fit.empty:
        fit = pd.DataFrame(columns=["item", "fit_n_clean"])

    out = pd.DataFrame({"item": candidates["item"].astype(str)})
    out = out.merge(summary[summary_keep], on="item", how="left")
    out = out.merge(fit, on="item", how="left")
    out["has_summary"] = out["summary_n_listings"].notna()
    out["has_fit"] = out["fit_n_clean"].notna()
    out["summary_ready"] = out["summary_n_listings"].fillna(0) >= min_summary_n
    out["fit_ready"] = out["fit_n_clean"].fillna(0) >= min_fit_clean
    out["model_ready"] = out["summary_ready"] & out["fit_ready"]
    out["needs_backfill"] = ~out["model_ready"]
    out["backfill_reason"] = out.apply(reason_text, axis=1)

    leading = [
        "item",
        "needs_backfill",
        "model_ready",
        "backfill_reason",
        "has_summary",
        "summary_ready",
        "summary_n_listings",
        "has_fit",
        "fit_ready",
        "fit_n_clean",
    ]
    ordered_cols = leading + [c for c in out.columns if c not in leading]
    out = out[ordered_cols].sort_values(
        ["needs_backfill", "summary_n_listings", "fit_n_clean", "item"],
        ascending=[False, True, True, True],
        na_position="first",
    )

    queue = out.loc[out["needs_backfill"]].copy().reset_index(drop=True)
    coverage_csv.parent.mkdir(parents=True, exist_ok=True)
    queue_csv.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(coverage_csv, index=False)
    queue.to_csv(queue_csv, index=False)
    write_items_py(queue["item"].astype(str).tolist(), queue_items_py, source_csv=queue_csv)

    print(f"config: {config_path}")
    print(f"risk candidates: {risk_candidates_csv} rows={len(candidates)}")
    print(f"summary: {summary_csv} rows={len(summary)}")
    print(f"fit json: {fit_json} items={len(fit)}")
    print(f"model ready: {int(out['model_ready'].sum())}")
    print(f"needs backfill: {len(queue)}")
    print(f"saved coverage: {coverage_csv}")
    print(f"saved queue csv: {queue_csv}")
    print(f"saved queue items py: {queue_items_py}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
