"""Run a small CSFloat model-data backfill batch.

This wrapper owns the automation-facing contract. It takes the backfill queue
from automation_runtime, writes a small ITEMS file, generates a skin_screener
runtime JSON from automation/configs/nightly.json, and runs skin_screener.py in
merge mode against skin_homog/data_skins_big.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from automation.config import load_json_config, nightly_defaults, path_from_config
from automation.listing_enrichment import load_items_py
from automation.risk_filters import repo_root_from


def configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass


def parse_args() -> argparse.Namespace:
    root = repo_root_from(Path(__file__))
    parser = argparse.ArgumentParser(description="Run a limited model-data backfill batch.")
    parser.add_argument(
        "--config",
        type=Path,
        default=root / "automation" / "configs" / "nightly.json",
        help="Nightly automation JSON config.",
    )
    parser.add_argument("--limit", type=int, default=None, help="Override model_backfill.max_items_per_run.")
    parser.add_argument("--dry-run", action="store_true", help="Print selected items and command without running.")
    return parser.parse_args()


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")


def write_items_py(items: list[str], path: Path, *, source_py: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by automation/nightly/run_model_backfill.py",
        f"# SOURCE_PY = {str(source_py)!r}",
        f"# N_OUTPUT_ITEMS = {len(items)}",
        "",
        "ITEMS = [",
    ]
    lines.extend(f"    {json.dumps(item, ensure_ascii=False)}," for item in items)
    lines.append("]")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def runtime_payload(config: dict) -> dict:
    cfg = config.get("model_backfill", {})
    return {
        "__comment": "Generated by automation/nightly/run_model_backfill.py. Edit automation/configs/nightly.json instead.",
        "DEFAULT_USE_MIX": bool(cfg.get("use_mix", True)),
        "DEFAULT_SKIP_KNOWN_IDS": bool(cfg.get("skip_known_ids", True)),
        "DEFAULT_IGNORE_EXISTING_ITEMS": bool(cfg.get("ignore_existing_items", True)),
        "DEFAULT_SORT": str(cfg.get("sort_by", "most_recent")),
        "TARGET_UNIQUE": int(cfg.get("target_unique", 400)),
        "PAGE_LIMIT": int(cfg.get("page_limit", 50)),
        "MIX_OVERFETCH_FACTOR": float(cfg.get("mix_overfetch_factor", 1.15)),
        "MIX_SHARDS": cfg.get("mix_shards", []),
        "INNER_DELAY_MIN": float(cfg.get("inner_delay_min_sec", 11.0)),
        "INNER_DELAY_MAX": float(cfg.get("inner_delay_max_sec", 16.8)),
        "ITEM_DELAY_MIN": float(cfg.get("item_delay_min_sec", 11.0)),
        "ITEM_DELAY_MAX": float(cfg.get("item_delay_max_sec", 16.0)),
        "SLOW_INNER_MIN": float(cfg.get("slow_inner_delay_min_sec", 16.0)),
        "SLOW_INNER_MAX": float(cfg.get("slow_inner_delay_max_sec", 21.0)),
        "SLOW_ITEM_MIN": float(cfg.get("slow_item_delay_min_sec", 16.0)),
        "SLOW_ITEM_MAX": float(cfg.get("slow_item_delay_max_sec", 21.0)),
        "SLOW_MODE_EXTEND_SEC": float(cfg.get("slow_mode_extend_sec", 1800.0)),
        "KEY_COOLDOWN_429_SEC": float(cfg.get("key_cooldown_429_sec", 1200.0)),
        "KEY_COOLDOWN_403_SEC": float(cfg.get("key_cooldown_403_sec", 1800.0)),
        "RETRY_LADDER_MIN_SEC": float(cfg.get("retry_ladder_min_sec", 90.0)),
        "RETRY_LADDER_STEP_SEC": float(cfg.get("retry_ladder_step_sec", 150.0)),
        "RETRY_LADDER_MAX_SEC": float(cfg.get("retry_ladder_max_sec", 900.0)),
    }


def write_runtime_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def build_command(config: dict, batch_items_py: Path) -> list[str]:
    cfg = config.get("model_backfill", {})
    mode = str(cfg.get("mode", "merge")).lower()
    if mode not in {"merge", "create"}:
        raise RuntimeError(f"Unsupported model_backfill.mode={mode!r}; expected merge or create")

    cmd = [
        sys.executable,
        str(repo_root_from(Path(__file__)) / "skin_homog" / "skin_screener.py"),
        f"--{mode}",
    ]
    cmd.append("--mix" if bool(cfg.get("use_mix", True)) else "--no-mix")
    cmd.extend(["--sort", str(cfg.get("sort_by", "most_recent"))])
    cmd.extend(["--target", str(int(cfg.get("target_unique", 400)))])
    cmd.append("--skip-known-ids" if bool(cfg.get("skip_known_ids", True)) else "--allow-known-ids")
    cmd.append("--ignore-existing-items" if bool(cfg.get("ignore_existing_items", True)) else "--allow-existing-items")
    cmd.append(str(batch_items_py))
    return cmd


def run_logged(cmd: list[str], *, cwd: Path, env: dict[str, str], log_path: Path) -> int:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as log:
        log.write("COMMAND:\n")
        log.write(" ".join(cmd) + "\n\n")
        log.flush()
        proc = subprocess.Popen(
            cmd,
            cwd=str(cwd),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        assert proc.stdout is not None
        for line in proc.stdout:
            print(line, end="")
            log.write(line)
            log.flush()
        return proc.wait()


def main() -> int:
    configure_stdio()
    args = parse_args()
    root = repo_root_from(Path(__file__))
    config_path = args.config.resolve()
    config = load_json_config(config_path, nightly_defaults())
    cfg = config.get("model_backfill", {})

    queue_items_py = path_from_config(config, "model_backfill_queue_items_py")
    batch_items_py = path_from_config(config, "model_backfill_batch_items_py")
    runtime_json = path_from_config(config, "model_backfill_runtime_json")
    progress_log = path_from_config(config, "model_backfill_progress_log")
    data_dir = path_from_config(config, "skin_data_dir")
    require_file(queue_items_py, "model backfill queue ITEMS file")
    if not data_dir.is_dir():
        raise FileNotFoundError(f"skin data dir not found: {data_dir}")

    limit = int(args.limit if args.limit is not None else cfg.get("max_items_per_run", 5))
    if limit < 1:
        raise RuntimeError(f"backfill limit must be >= 1, got {limit}")

    queue = load_items_py(queue_items_py)
    selected = queue[:limit]
    runtime_cfg = runtime_payload(config)
    cmd = build_command(config, batch_items_py)

    print(f"config: {config_path}")
    print(f"queue items py: {queue_items_py} items={len(queue)}")
    print(f"batch items py: {batch_items_py}")
    print(f"selected items: {len(selected)}")
    for idx, item in enumerate(selected, start=1):
        print(f"  {idx}. {item}")
    print(f"skin data dir: {data_dir}")
    print(f"runtime JSON: {runtime_json}")
    print(f"progress log: {progress_log}")
    print(
        "timing: "
        f"inner={runtime_cfg['INNER_DELAY_MIN']}..{runtime_cfg['INNER_DELAY_MAX']}s "
        f"item={runtime_cfg['ITEM_DELAY_MIN']}..{runtime_cfg['ITEM_DELAY_MAX']}s "
        f"slow_item={runtime_cfg['SLOW_ITEM_MIN']}..{runtime_cfg['SLOW_ITEM_MAX']}s "
        f"429_cooldown={runtime_cfg['KEY_COOLDOWN_429_SEC']}s"
    )
    print("command:")
    print(" ".join(cmd))

    if not selected:
        print("backfill queue is empty; nothing to do")
        return 0
    if args.dry_run:
        return 0

    write_items_py(selected, batch_items_py, source_py=queue_items_py)
    write_runtime_json(runtime_json, runtime_cfg)
    env = os.environ.copy()
    env["SKIN_SCREENER_RUNTIME_CONFIG"] = str(runtime_json)
    env["SKIN_SCREENER_OUTPUT_DIR"] = str(data_dir)
    env["PYTHONIOENCODING"] = "utf-8"
    env["PYTHONUTF8"] = "1"

    rc = run_logged(cmd, cwd=root, env=env, log_path=progress_log)
    if rc != 0:
        print(f"model backfill failed with exit code {rc}", file=sys.stderr)
        return rc
    print("model backfill completed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
